language: php

php:
- 7.1
- 7.2
- 7.3

before_script:
- composer self-update
- composer install
- chmod 777 ./preparePHPUnit.php
- php ./preparePHPUnit.php
- chmod 777 ./phpunit.phar

script:
- ./phpunit.phar
